global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "eventos-monitor"
    environment: "production"

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  # Sistema de Gestão de Eventos - Backend (múltiplas instâncias)
  - job_name: "eventos-backend"
    static_configs:
      - targets:
          - "backend:8000"
          # Adicione mais instâncias aqui em produção
          # - 'backend2:8000'
          # - 'backend3:8000'
    metrics_path: "/metrics"
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ["prometheus"]

  # PostgreSQL com múltiplas métricas
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]
    scrape_interval: 15s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: "([^:]+):.+"
        replacement: "${1}"

  # Redis Cluster
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
    scrape_interval: 15s

  # Node Exporter para múltiplos hosts
  - job_name: "node"
    static_configs:
      - targets:
          - "node-exporter:9100"
    scrape_interval: 15s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: "([^:]+):.+"
        replacement: "${1}"

  # Nginx com métricas detalhadas
  - job_name: "nginx"
    static_configs:
      - targets: ["nginx-exporter:9113"]
    scrape_interval: 15s

  # cAdvisor para métricas de containers
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
    scrape_interval: 15s
    metrics_path: "/metrics"

  # Blackbox exporter para health checks externos
  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://your-domain.com
          - https://your-domain.com/api/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Prometheus self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    scrape_interval: 15s

  # Grafana metrics
  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]
    metrics_path: "/metrics"
    scrape_interval: 30s
